#!/usr/bin/env bash
# build.sh — Build Pushling and wrap it into a proper macOS .app bundle
#
# Usage:
#   ./build.sh              # Debug build, auto-increment build number
#   ./build.sh release      # Release build (optimized)
#   ./build.sh patch        # Bump patch version (0.1.0 → 0.1.1)
#   ./build.sh minor        # Bump minor version (0.1.1 → 0.2.0)
#   ./build.sh major        # Bump major version (0.2.0 → 1.0.0)
#
# Version is stored in .build-version and auto-increments the build
# number on every run. Patch/minor/major bump the semver component
# and reset lower components to 0.
#
# Output: build/Pushling.app

set -euo pipefail

# --- Configuration ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPM_DIR="${SCRIPT_DIR}/Pushling"
BUILD_DIR="${SCRIPT_DIR}/build"
APP_BUNDLE="${BUILD_DIR}/Pushling.app"
CONTENTS_DIR="${APP_BUNDLE}/Contents"
MACOS_DIR="${CONTENTS_DIR}/MacOS"
RESOURCES_DIR="${CONTENTS_DIR}/Resources"
VERSION_FILE="${SCRIPT_DIR}/.build-version"

# --- Version Management ---
# Format: MAJOR.MINOR.PATCH.BUILD
# BUILD auto-increments on every run. Patch/minor/major bump semver.

if [ -f "${VERSION_FILE}" ]; then
    CURRENT_VERSION="$(cat "${VERSION_FILE}")"
else
    CURRENT_VERSION="0.1.0.0"
fi

IFS='.' read -r V_MAJOR V_MINOR V_PATCH V_BUILD <<< "${CURRENT_VERSION}"
V_MAJOR="${V_MAJOR:-0}"
V_MINOR="${V_MINOR:-1}"
V_PATCH="${V_PATCH:-0}"
V_BUILD="${V_BUILD:-0}"

# Parse arguments — first arg can be config or version bump
CONFIG="debug"
BUMP=""
for arg in "$@"; do
    case "${arg}" in
        release|Release) CONFIG="release" ;;
        debug|Debug)     CONFIG="debug" ;;
        patch)           BUMP="patch" ;;
        minor)           BUMP="minor" ;;
        major)           BUMP="major" ;;
    esac
done

# Apply version bump if requested
case "${BUMP}" in
    patch)
        V_PATCH=$(( V_PATCH + 1 ))
        V_BUILD=0
        ;;
    minor)
        V_MINOR=$(( V_MINOR + 1 ))
        V_PATCH=0
        V_BUILD=0
        ;;
    major)
        V_MAJOR=$(( V_MAJOR + 1 ))
        V_MINOR=0
        V_PATCH=0
        V_BUILD=0
        ;;
esac

# Always increment build number
V_BUILD=$(( V_BUILD + 1 ))

VERSION="${V_MAJOR}.${V_MINOR}.${V_PATCH}.${V_BUILD}"
SEMVER="${V_MAJOR}.${V_MINOR}.${V_PATCH}"

# Persist version
echo "${VERSION}" > "${VERSION_FILE}"

# --- Build ---
case "${CONFIG}" in
    release)
        SWIFT_FLAGS="-c release"
        ;;
    *)
        SWIFT_FLAGS="-c debug"
        ;;
esac

echo "==> Pushling v${VERSION}${BUMP:+ (${BUMP} bump)} — ${CONFIG}"
echo ""

# --- Step 0.5: Sync PushlingVersion.swift with build version ---
VERSION_SWIFT="${SPM_DIR}/Sources/Pushling/App/PushlingVersion.swift"
cat > "${VERSION_SWIFT}" << VSWIFT
// PushlingVersion.swift — Single source of truth for app version
// AUTO-GENERATED by build.sh — do not edit manually

enum PushlingVersion {
    static let major = ${V_MAJOR}
    static let minor = ${V_MINOR}
    static let patch = ${V_PATCH}
    static let build = ${V_BUILD}

    static let string = "\(major).\(minor).\(patch).\(build)"
}
VSWIFT

# --- Step 1: Build with Swift Package Manager ---
# Clean stale object files to prevent incremental build cache bugs
# (SPM sometimes serves stale .o files when only function bodies change)
echo "    [1/5] swift build ${SWIFT_FLAGS}"
cd "${SPM_DIR}"
swift package clean 2>/dev/null || true
swift build ${SWIFT_FLAGS} 2>&1

# Find the built binary
BIN_PATH="$(swift build ${SWIFT_FLAGS} --show-bin-path)/Pushling"
if [ ! -f "${BIN_PATH}" ]; then
    echo "ERROR: Built binary not found at ${BIN_PATH}"
    exit 1
fi
echo "    Built: ${BIN_PATH}"

# --- Step 2: Create .app bundle structure ---
echo "    [2/5] Creating .app bundle structure..."
rm -rf "${APP_BUNDLE}"
mkdir -p "${MACOS_DIR}"
mkdir -p "${RESOURCES_DIR}"

# --- Step 3: Generate Info.plist ---
echo "    [3/5] Generating Info.plist..."

GIT_HASH="$(git -C "${SCRIPT_DIR}" rev-parse --short HEAD 2>/dev/null || echo "dev")"
BUILD_DATE="$(date -u +%Y%m%d)"

cat > "${CONTENTS_DIR}/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>

    <key>CFBundleExecutable</key>
    <string>Pushling</string>

    <key>CFBundleIdentifier</key>
    <string>com.pushling.app</string>

    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>

    <key>CFBundleName</key>
    <string>Pushling</string>

    <key>CFBundleDisplayName</key>
    <string>Pushling</string>

    <key>CFBundlePackageType</key>
    <string>APPL</string>

    <key>CFBundleShortVersionString</key>
    <string>${SEMVER}</string>

    <key>CFBundleVersion</key>
    <string>${V_BUILD}</string>

    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>

    <key>LSUIElement</key>
    <true/>

    <key>NSPrincipalClass</key>
    <string>NSApplication</string>

    <key>NSHighResolutionCapable</key>
    <true/>

    <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>

    <key>CFBundleIconFile</key>
    <string></string>
</dict>
</plist>
PLIST

# --- Step 4: Copy binary and resources ---
echo "    [4/5] Copying binary and resources..."

cp "${BIN_PATH}" "${MACOS_DIR}/Pushling"
chmod +x "${MACOS_DIR}/Pushling"

if [ -f "${SPM_DIR}/Resources/com.pushling.daemon.plist" ]; then
    cp "${SPM_DIR}/Resources/com.pushling.daemon.plist" "${RESOURCES_DIR}/"
fi

for ext in png jpg wav mp3 json; do
    find "${SPM_DIR}/Resources" -name "*.${ext}" -exec cp {} "${RESOURCES_DIR}/" \; 2>/dev/null || true
done

# --- Step 5: Ad-hoc code sign ---
echo "    [5/5] Ad-hoc code signing..."
codesign --force --sign - --deep "${APP_BUNDLE}" 2>&1

# --- Step 6: Deploy to /Applications and restart ---
INSTALLED_APP="/Applications/Pushling.app"
if [ -d "${INSTALLED_APP}" ]; then
    echo "    [6/6] Deploying to ${INSTALLED_APP}..."
    # Kill running instance and wait for it to actually die
    if pgrep -x Pushling >/dev/null 2>&1; then
        killall Pushling 2>/dev/null || true
        # Wait up to 3 seconds for process to exit
        for i in 1 2 3 4 5 6; do
            pgrep -x Pushling >/dev/null 2>&1 || break
            sleep 0.5
        done
        # Force kill if still alive
        killall -9 Pushling 2>/dev/null || true
        sleep 0.5
    fi
    rsync -a --delete "${APP_BUNDLE}/" "${INSTALLED_APP}/"
    # Relaunch
    open "${INSTALLED_APP}"
    echo "    Deployed and relaunched"
else
    echo "    [6/6] Installing to ${INSTALLED_APP}..."
    cp -R "${APP_BUNDLE}" "${INSTALLED_APP}"
    open "${INSTALLED_APP}"
    echo "    Installed and launched"
fi

# --- Done ---
echo ""
echo "==> Build complete: ${APP_BUNDLE}"
echo "    Bundle ID:  com.pushling.app"
echo "    Version:    ${VERSION} (${SEMVER} build ${V_BUILD})"
echo "    Git:        ${GIT_HASH} (${BUILD_DATE})"
echo "    Config:     ${CONFIG}"
echo "    LSUIElement: true (no dock icon)"
echo ""
echo "    To run:  open ${APP_BUNDLE}"
echo "    Or:      ./run.sh"
