// PushlingVersion.swift — Single source of truth for app version
// AUTO-GENERATED by build.sh — do not edit manually

enum PushlingVersion {
    static let major = 0
    static let minor = 1
    static let patch = 0
    static let build = 32

    static let string = "\(major).\(minor).\(patch).\(build)"
}
